export default function TermsPage({ onBack }) {
  return (
    <div className="about-page">
      <div className="about-inner">

        <button className="prf-top-back" onClick={onBack}>← Back to Game</button>

        <div className="about-header">
          <div className="about-title">Terms of <em>Service</em></div>
          <div className="about-subtitle">Effective date: August 8, 2026</div>
        </div>

        <section className="about-section">
          <h2 className="about-section-title">1. Non-Affiliation</h2>
          <p className="about-body">
            Build-A-Player is an independent fan project and is not affiliated with, endorsed by, or sponsored by the National Football League, NFL Properties LLC, the NBA, or any of their member teams, players' associations, or players. Player and team names are used for informational and entertainment purposes only. All team and league trademarks remain the property of their respective owners.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">2. About the Service</h2>
          <p className="about-body">
            Build-A-Player is a free fan-made fantasy sports game. You draft attributes from real NFL or NBA players, an algorithm simulates a season, and you receive a fictional record you can compare on leaderboards and share. The Service is provided for entertainment purposes only.
          </p>
          <p className="about-body">
            Simulation results are fictional and generated by an algorithm. They do not represent, predict, or reflect the actual or likely performance of any real player, team, or game. We make no representations about the accuracy or methodology of the simulation or of any statistics shown.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">3. No Gambling</h2>
          <p className="about-body">
            The Service does not involve gambling, wagering, betting, or real-money play of any kind. No purchase is necessary to use the core game. Leaderboard placements and simulation records have no monetary value and cannot be exchanged for money or any other consideration. The Service is not a sports betting, daily fantasy sports, or prediction product and must not be used as a basis for any wagering decision.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">4. Eligibility</h2>
          <p className="about-body">
            You must be at least 13 years old to use the Service. If you are under the age of majority in your jurisdiction, you may use the Service only with the consent of a parent or legal guardian. By using the Service, you represent that you meet these requirements.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">5. Build-A-Player Plus (Subscription)</h2>
          <p className="about-body">
            Build-A-Player Plus is an optional subscription at $4.99/month that removes ads and unlocks additional features including custom color themes, custom profile icons, and a PLUS badge on leaderboard entries. Subscriptions are billed monthly and renew automatically unless cancelled. You may cancel at any time through your profile page or by contacting us at <a href="mailto:buildaplayer@outlook.com" className="about-link">buildaplayer@outlook.com</a>. Cancellation takes effect at the end of the current billing period. We do not offer refunds for partial months.
          </p>
          <p className="about-body">
            Payments are processed by Stripe. We do not store your payment card details. Subscription management is available via the billing portal accessible from your profile.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">6. Acceptable Use</h2>
          <p className="about-body">You agree not to:</p>
          <ul className="about-list">
            <li>Use bots, scripts, or automation tools to play the game, manipulate records, or exploit leaderboards.</li>
            <li>Create multiple accounts to gain an unfair advantage in head-to-head matchmaking or on leaderboards.</li>
            <li>Exploit bugs or unintended behavior. If you discover one, please report it to us.</li>
            <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation.</li>
          </ul>
          <p className="about-body">
            We may suspend or terminate access for violations of this section, with or without notice.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">7. User Accounts</h2>
          <p className="about-body">
            You must choose a username that does not impersonate another person. You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account. We reserve the right to suspend or terminate accounts that violate these Terms.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">8. Disclaimer of Warranties</h2>
          <p className="about-body">
            The Service is provided "as is" and "as available" without warranties of any kind. We do not guarantee uninterrupted availability, accuracy of simulation results, or permanence of leaderboard data. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">9. Limitation of Liability</h2>
          <p className="about-body">
            To the maximum extent permitted by law, Build-A-Player and its operators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months prior to the claim, or $10, whichever is greater.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">10. Indemnification</h2>
          <p className="about-body">
            You agree to indemnify and hold harmless Build-A-Player and its operators from and against any claims, damages, losses, and expenses, including reasonable attorneys' fees, arising out of your use of the Service or your violation of these Terms.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">11. Governing Law</h2>
          <p className="about-body">
            These Terms are governed by the laws of the State of Georgia, without regard to its conflict of laws principles. Any dispute arising out of or relating to these Terms or the Service shall be subject to the exclusive jurisdiction of the state and federal courts located in Georgia.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">12. Changes to These Terms</h2>
          <p className="about-body">
            We may update these Terms from time to time. Changes will be posted on this page with an updated effective date. Continued use of the Service after changes take effect constitutes acceptance of the revised Terms. If any provision of these Terms is held unenforceable, the remaining provisions will remain in full force.
          </p>
        </section>

        <section className="about-section">
          <h2 className="about-section-title">13. Contact</h2>
          <p className="about-body">
            Questions? Reach us at <a href="mailto:buildaplayer@outlook.com" className="about-link">buildaplayer@outlook.com</a>
          </p>
        </section>


      </div>
    </div>
  )
}
